### PR TITLE
Updated gifs because of a visual bug in example 2

### PR DESCRIPTION
**Pull request by dejorrit**
@mattijsbliek Updated the gifs for both examples because the second example had a visual bug: placeholder was visible behind the label in the Expiry Date input

### CODE REVIEW

**Comment by mattijsbliek** [comment]
The second file seems incorrect, the placeholder is but on top of the value after you tab out of the field 🤔

**Comment by dejorrit** [comment]
@mattijsbliek wow, how did I not notice that 😬 Turned out we had a little bug with toggling the `is-dirty` class, fixed it here: https://github.com/mollie/components-examples/pull/3

**Comment by mattijsbliek** [comment]
Just merged the other PR. If you can do a new gif I think we’re good to go 🚀

**Comment by dejorrit** [comment]
@mattijsbliek Gif is updated!

**Review by mattijsbliek — APPROVED** [review]
Nice! Ship it 👍

**Pull request merged**
